/**
 * Auto-generated by scripts/generate-metadata.ts - do not edit by hand.
 * Source: Bundled Command Code CLI model registry (command-code-knowledge/reference/models.md) + commandcode.ai/docs/resources/pricing-limits capability badges
 * Verified: 2026-09-19
 */

import type { ModelCost } from "@earendil-works/pi-ai";
import { DEFAULT_MAX_OUTPUT_TOKENS } from "./constants.ts";

export const METADATA_LAST_VERIFIED = "2026-09-19";

export const ZERO_COST: ModelCost = { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 };

export interface CatalogModelMetadata {
  reasoning: boolean;
  efforts?: readonly string[];
  input: ("text" | "image")[];
  maxOutputTokens: number;
  cost: ModelCost;
}

export const CATALOG_METADATA: Record<string, CatalogModelMetadata> = {
  "MiniMaxAI/MiniMax-M2.5": {
    reasoning: false,
    input: ["text"],
    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,
    cost: { input: 0.3, output: 1.2, cacheRead: 0.03, cacheWrite: 0 },
  },
  "MiniMaxAI/MiniMax-M2.7": {
    reasoning: false,
    input: ["text"],
    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,
    cost: { input: 0.3, output: 1.2, cacheRead: 0.06, cacheWrite: 0 },
  },
  "MiniMaxAI/MiniMax-M3": {
    reasoning: true,
    efforts: ["low", "medium", "high"],
    input: ["text"],
    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,
    cost: { input: 0.3, output: 1.2, cacheRead: 0.06, cacheWrite: 0 },
  },
  "Qwen/Qwen3.6-Max-Preview": {
    reasoning: true,
    input: ["text"],
    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,
    cost: { input: 1.3, output: 7.8, cacheRead: 0.26, cacheWrite: 1.63 },
  },
  "Qwen/Qwen3.6-Plus": {
    reasoning: true,
    input: ["text", "image"],
    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,
    cost: { input: 0.5, output: 3, cacheRead: 0.1, cacheWrite: 0 },
  },
  "Qwen/Qwen3.7-Flash": {
    reasoning: true,
    input: ["text", "image"],
    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,
    cost: { input: 0.03, output: 0.13, cacheRead: 0.006, cacheWrite: 0.038 },
  },
  "Qwen/Qwen3.7-Max": {
    reasoning: true,
    input: ["text"],
    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,
    cost: { input: 2.5, output: 7.5, cacheRead: 0.5, cacheWrite: 3.13 },
  },
  "Qwen/Qwen3.7-Plus": {
    reasoning: true,
    input: ["text", "image"],
    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,
    cost: { input: 0.4, output: 1.6, cacheRead: 0.08, cacheWrite: 0.5 },
  },
  "Qwen/Qwen3.8-27B": {
    reasoning: true,
    efforts: ["low", "medium", "xhigh"],
    input: ["text", "image"],
    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,
    cost: { input: 0.4, output: 3, cacheRead: 0.04, cacheWrite: 0 },
  },
  "Qwen/Qwen3.8-Flash": {
    reasoning: true,
    efforts: ["low", "medium", "xhigh"],
    input: ["text", "image"],
    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,
    cost: { input: 0.16, output: 0.47, cacheRead: 0.016, cacheWrite: 0 },
  },
  "Qwen/Qwen3.8-Max": {
    reasoning: true,
    efforts: ["low", "medium", "xhigh"],
    input: ["text", "image"],
    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,
    cost: { input: 2, output: 6, cacheRead: 0.25, cacheWrite: 2.5 },
  },
  "Qwen/Qwen3.8-Max-0902": {
    reasoning: true,
    efforts: ["low", "medium", "xhigh"],
    input: ["text", "image"],
    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,
    cost: { input: 2, output: 6, cacheRead: 0.25, cacheWrite: 0 },
  },
  "Qwen/Qwen3.8-Omni-Flash": {
    reasoning: true,
    efforts: ["low", "medium", "xhigh"],
    input: ["text", "image"],
    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,
    cost: { input: 0.15, output: 0.47, cacheRead: 0.016, cacheWrite: 0 },
  },
  "claude-fable-5": {
    reasoning: true,
    efforts: ["low", "medium", "high", "xhigh", "max"],
    input: ["text", "image"],
    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,
    cost: { input: 10, output: 50, cacheRead: 1, cacheWrite: 12.5 },
  },
  "claude-fable-5-1": {
    reasoning: true,
    efforts: ["low", "medium", "high", "xhigh", "max"],
    input: ["text", "image"],
    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,
    cost: { input: 10, output: 50, cacheRead: 0.25, cacheWrite: 12.5 },
  },
  "claude-haiku-4-5-20251001": {
    reasoning: false,
    input: ["text", "image"],
    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,
    cost: { input: 1, output: 5, cacheRead: 0.1, cacheWrite: 1.25 },
  },
  "claude-opus-4-7": {
    reasoning: true,
    efforts: ["low", "medium", "high", "xhigh", "max"],
    input: ["text", "image"],
    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,
    cost: { input: 5, output: 25, cacheRead: 0.5, cacheWrite: 6.25 },
  },
  "claude-opus-4-8": {
    reasoning: true,
    efforts: ["low", "medium", "high", "xhigh", "max"],
    input: ["text", "image"],
    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,
    cost: { input: 5, output: 25, cacheRead: 0.5, cacheWrite: 6.25 },
  },
  "claude-opus-5": {
    reasoning: true,
    efforts: ["low", "medium", "high", "xhigh", "max"],
    input: ["text", "image"],
    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,
    cost: { input: 5, output: 25, cacheRead: 0.5, cacheWrite: 6.25 },
  },
  "claude-sonnet-4-6": {
    reasoning: true,
    efforts: ["low", "medium", "high", "xhigh", "max"],
    input: ["text", "image"],
    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,
    cost: { input: 3, output: 15, cacheRead: 0.3, cacheWrite: 3.75 },
  },
  "claude-sonnet-5": {
    reasoning: true,
    efforts: ["low", "medium", "high", "xhigh", "max"],
    input: ["text", "image"],
    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,
    cost: { input: 2, output: 10, cacheRead: 0.2, cacheWrite: 2.5 },
  },
  "deepseek/deepseek-v4-flash": {
    reasoning: true,
    efforts: ["high", "max"],
    input: ["text"],
    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,
    cost: { input: 0.15, output: 0.6, cacheRead: 0.003, cacheWrite: 0 },
  },
  "deepseek/deepseek-v4-flash-fast": {
    reasoning: true,
    efforts: ["low", "high", "max"],
    input: ["text"],
    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,
    cost: { input: 0.28, output: 0.56, cacheRead: 0.07, cacheWrite: 0 },
  },
  "deepseek/deepseek-v4-flash-vision-exp": {
    reasoning: true,
    efforts: ["high", "max"],
    input: ["text", "image"],
    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,
    cost: { input: 0.15, output: 0.6, cacheRead: 0.003, cacheWrite: 0 },
  },
  "deepseek/deepseek-v4-pro": {
    reasoning: true,
    efforts: ["high", "max"],
    input: ["text"],
    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,
    cost: { input: 0.66, output: 1.98, cacheRead: 0.022, cacheWrite: 0 },
  },
  "deepseek/deepseek-v4.1-flash": {
    reasoning: true,
    efforts: ["low", "high", "max"],
    input: ["text", "image"],
    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,
    cost: { input: 0.15, output: 0.6, cacheRead: 0.003, cacheWrite: 0 },
  },
  "google/gemini-3.1-flash-lite": {
    reasoning: true,
    efforts: ["low", "medium", "high"],
    input: ["text", "image"],
    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,
    cost: { input: 0.25, output: 1.5, cacheRead: 0.03, cacheWrite: 0 },
  },
  "google/gemini-3.5-flash": {
    reasoning: true,
    efforts: ["low", "medium", "high"],
    input: ["text", "image"],
    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,
    cost: { input: 1.5, output: 9, cacheRead: 0.15, cacheWrite: 0 },
  },
  "google/gemini-3.5-flash-lite": {
    reasoning: true,
    efforts: ["low", "medium", "high"],
    input: ["text", "image"],
    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,
    cost: { input: 0.3, output: 2.5, cacheRead: 0.03, cacheWrite: 0 },
  },
  "google/gemini-3.6-flash": {
    reasoning: true,
    efforts: ["low", "medium", "high"],
    input: ["text", "image"],
    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,
    cost: { input: 1.5, output: 7.5, cacheRead: 0.15, cacheWrite: 0 },
  },
  "google/gemini-3.7-flash": {
    reasoning: true,
    efforts: ["low", "medium", "high"],
    input: ["text", "image"],
    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,
    cost: { input: 1.5, output: 7.5, cacheRead: 0.15, cacheWrite: 0.08334 },
  },
  "google/gemini-3.8-flash": {
    reasoning: true,
    efforts: ["low", "medium", "high"],
    input: ["text", "image"],
    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,
    cost: { input: 1.5, output: 7.5, cacheRead: 0.15, cacheWrite: 0 },
  },
  "gpt-5.3-codex": {
    reasoning: true,
    efforts: ["low", "medium", "high", "xhigh"],
    input: ["text", "image"],
    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,
    cost: { input: 2, output: 8, cacheRead: 0.5, cacheWrite: 0 },
  },
  "gpt-5.4": {
    reasoning: true,
    efforts: ["low", "medium", "high", "xhigh"],
    input: ["text", "image"],
    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,
    cost: { input: 2.5, output: 15, cacheRead: 0.25, cacheWrite: 0 },
  },
  "gpt-5.4-mini": {
    reasoning: true,
    efforts: ["low", "medium", "high"],
    input: ["text", "image"],
    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,
    cost: { input: 0.75, output: 4.5, cacheRead: 0.075, cacheWrite: 0 },
  },
  "gpt-5.5": {
    reasoning: true,
    efforts: ["low", "medium", "high", "xhigh"],
    input: ["text", "image"],
    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,
    cost: { input: 5, output: 30, cacheRead: 0.5, cacheWrite: 0 },
  },
  "gpt-5.6-luna": {
    reasoning: true,
    efforts: ["low", "medium", "high", "xhigh", "max"],
    input: ["text", "image"],
    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,
    cost: { input: 0.2, output: 1.2, cacheRead: 0.02, cacheWrite: 0.25 },
  },
  "gpt-5.6-sol": {
    reasoning: true,
    efforts: ["low", "medium", "high", "xhigh", "max"],
    input: ["text", "image"],
    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,
    cost: { input: 5, output: 30, cacheRead: 0.5, cacheWrite: 6.25 },
  },
  "gpt-5.6-terra": {
    reasoning: true,
    efforts: ["low", "medium", "high", "xhigh", "max"],
    input: ["text", "image"],
    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,
    cost: { input: 2, output: 12, cacheRead: 0.2, cacheWrite: 2.5 },
  },
  "gpt-6-astra": {
    reasoning: true,
    efforts: ["low", "medium", "high", "xhigh", "max"],
    input: ["text", "image"],
    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,
    cost: { input: 10, output: 50, cacheRead: 1, cacheWrite: 12.5 },
  },
  "inclusionai/ling-3.0-flash-sante:free": {
    reasoning: false,
    input: ["text"],
    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,
    cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
  },
  "meituan/LongCat-2.0": {
    reasoning: true,
    input: ["text"],
    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,
    cost: { input: 0.3, output: 1.2, cacheRead: 0.006, cacheWrite: 0 },
  },
  "meta/muse-spark-1.1": {
    reasoning: true,
    efforts: ["low", "medium", "high", "xhigh"],
    input: ["text", "image"],
    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,
    cost: { input: 1.25, output: 4.25, cacheRead: 0.15, cacheWrite: 0 },
  },
  "meta/muse-spark-1.2": {
    reasoning: true,
    efforts: ["low", "medium", "high", "xhigh"],
    input: ["text", "image"],
    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,
    cost: { input: 1.25, output: 4.25, cacheRead: 0.15, cacheWrite: 0 },
  },
  "meta/muse-spark-1.2-contributor": {
    reasoning: true,
    efforts: ["low", "medium", "high", "xhigh"],
    input: ["text", "image"],
    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,
    cost: { input: 0.1, output: 0.2, cacheRead: 0.002, cacheWrite: 0 },
  },
  "meta/muse-spark-1.3": {
    reasoning: true,
    efforts: ["low", "medium", "high", "xhigh", "max"],
    input: ["text", "image"],
    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,
    cost: { input: 1.25, output: 4.25, cacheRead: 0.15, cacheWrite: 0 },
  },
  "meta/muse-spark-1.3-contributor": {
    reasoning: true,
    efforts: ["low", "medium", "high", "xhigh"],
    input: ["text", "image"],
    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,
    cost: { input: 0.1, output: 0.2, cacheRead: 0.002, cacheWrite: 0 },
  },
  "moonshotai/Kimi-K2.5": {
    reasoning: false,
    input: ["text", "image"],
    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,
    cost: { input: 0.6, output: 3, cacheRead: 0.1, cacheWrite: 0 },
  },
  "moonshotai/Kimi-K2.6": {
    reasoning: false,
    input: ["text", "image"],
    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,
    cost: { input: 0.95, output: 4, cacheRead: 0.16, cacheWrite: 0 },
  },
  "moonshotai/Kimi-K2.7-Code": {
    reasoning: true,
    input: ["text", "image"],
    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,
    cost: { input: 0.95, output: 4, cacheRead: 0.19, cacheWrite: 0 },
  },
  "moonshotai/Kimi-K2.7-Code-Highspeed": {
    reasoning: true,
    input: ["text", "image"],
    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,
    cost: { input: 1.9, output: 8, cacheRead: 0.38, cacheWrite: 0 },
  },
  "moonshotai/Kimi-K3": {
    reasoning: true,
    efforts: ["low", "high", "max"],
    input: ["text", "image"],
    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,
    cost: { input: 3, output: 15, cacheRead: 0.3, cacheWrite: 0 },
  },
  "nvidia/nemotron-3-ultra-550b-a55b": {
    reasoning: true,
    input: ["text"],
    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,
    cost: { input: 0.6, output: 2.4, cacheRead: 0.12, cacheWrite: 0 },
  },
  "poolside/laguna-s-2.1-free": {
    reasoning: false,
    input: ["text"],
    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,
    cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
  },
  "sakana/fugu-ultra": {
    reasoning: true,
    efforts: ["high", "xhigh"],
    input: ["text", "image"],
    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,
    cost: { input: 5, output: 30, cacheRead: 0.5, cacheWrite: 0 },
  },
  "stepfun/Step-3.5-Flash": {
    reasoning: true,
    input: ["text"],
    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,
    cost: { input: 0.1, output: 0.3, cacheRead: 0.02, cacheWrite: 0 },
  },
  "stepfun/Step-3.7-Flash": {
    reasoning: true,
    input: ["text", "image"],
    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,
    cost: { input: 0.2, output: 1.15, cacheRead: 0.04, cacheWrite: 0 },
  },
  "tencent/hy3-paid": {
    reasoning: true,
    input: ["text"],
    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,
    cost: { input: 0.14, output: 0.58, cacheRead: 0.035, cacheWrite: 0 },
  },
  "tencent/hy4-preview": {
    reasoning: true,
    efforts: ["low", "medium", "high"],
    input: ["text"],
    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,
    cost: { input: 0.834, output: 2.501, cacheRead: 0.042, cacheWrite: 0 },
  },
  "thinkingmachines/inkling": {
    reasoning: true,
    input: ["text", "image"],
    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,
    cost: { input: 1, output: 4.05, cacheRead: 0.17, cacheWrite: 0 },
  },
  "thinkingmachines/inkling-small": {
    reasoning: true,
    input: ["text", "image"],
    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,
    cost: { input: 0.5, output: 1.2, cacheRead: 0.1, cacheWrite: 0 },
  },
  "xai/grok-4.5": {
    reasoning: true,
    efforts: ["low", "medium", "high"],
    input: ["text", "image"],
    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,
    cost: { input: 2, output: 6, cacheRead: 0.5, cacheWrite: 0 },
  },
  "xai/grok-4.6": {
    reasoning: true,
    efforts: ["low", "medium", "high", "xhigh"],
    input: ["text", "image"],
    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,
    cost: { input: 2, output: 6, cacheRead: 0.5, cacheWrite: 0 },
  },
  "xiaomi/mimo-v2.5": {
    reasoning: false,
    input: ["text"],
    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,
    cost: { input: 0.14, output: 0.28, cacheRead: 0.0028, cacheWrite: 0 },
  },
  "xiaomi/mimo-v2.5-pro": {
    reasoning: false,
    input: ["text"],
    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,
    cost: { input: 0.435, output: 0.87, cacheRead: 0.0036, cacheWrite: 0 },
  },
  "z-ai/glm-5.3-flash": {
    reasoning: true,
    efforts: ["low", "high", "max"],
    input: ["text", "image"],
    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,
    cost: { input: 0.15, output: 0.5, cacheRead: 0.03, cacheWrite: 0 },
  },
  "z-ai/glm-5.3-flashx": {
    reasoning: true,
    efforts: ["low", "high", "max"],
    input: ["text", "image"],
    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,
    cost: { input: 0.37, output: 1.25, cacheRead: 0.075, cacheWrite: 0 },
  },
  "zai-org/GLM-5": {
    reasoning: false,
    input: ["text"],
    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,
    cost: { input: 1, output: 3.2, cacheRead: 0.2, cacheWrite: 0 },
  },
  "zai-org/GLM-5.1": {
    reasoning: false,
    input: ["text"],
    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,
    cost: { input: 1.4, output: 4.4, cacheRead: 0.26, cacheWrite: 0 },
  },
  "zai-org/GLM-5.2": {
    reasoning: true,
    efforts: ["high", "max"],
    input: ["text"],
    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,
    cost: { input: 1.4, output: 4.4, cacheRead: 0.26, cacheWrite: 0 },
  },
  "zai-org/GLM-5.2-Fast": {
    reasoning: false,
    input: ["text"],
    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,
    cost: { input: 3, output: 10.25, cacheRead: 0.5, cacheWrite: 0 },
  },
  "zai-org/GLM-5.3": {
    reasoning: true,
    efforts: ["low", "high", "max"],
    input: ["text"],
    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,
    cost: { input: 1.4, output: 4.4, cacheRead: 0.26, cacheWrite: 0 },
  },
};

/**
 * Static metadata for a model id. Unknown ids degrade to a text-only,
 * non-reasoning model with zero cost and the default output-token budget;
 * callers clamp maxTokens against the catalog's context_length.
 */
export function metadataForModel(id: string): CatalogModelMetadata {
  if (Object.hasOwn(CATALOG_METADATA, id)) return CATALOG_METADATA[id];
  return { reasoning: false, input: ["text"], maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS, cost: ZERO_COST };
}
