/**
 * Regenerate `models.generated.ts` (the baked fallback catalog) and
 * `pricing.generated.ts` from the public model catalog merged with the static
 * metadata snapshot.
 *
 * Online:  `npm run generate-models` fetches `GET /provider/v1/models` (public,
 *          no credential).
 * Offline: `npm run generate-models -- --from-file scripts/models.snapshot.json`
 *          reads a checked-in catalog snapshot instead, so generation is
 *          reproducible without network access.
 *
 * Output is sorted by model id and formatted with biome (best effort), so the
 * result is deterministic.
 */

import { spawnSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import type { ModelCost } from "@earendil-works/pi-ai";
import type { ProviderModelConfig } from "@earendil-works/pi-coding-agent";
import { CATALOG_METADATA, METADATA_LAST_VERIFIED } from "../catalog.metadata.ts";
import { assembleModels, fetchCommandCodeModels, parseCommandCodeCatalog } from "../models.ts";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, "..");
const MODELS_FILE = join(ROOT, "models.generated.ts");
const PRICING_FILE = join(ROOT, "pricing.generated.ts");

function readArg(name: string): string | undefined {
  const index = process.argv.indexOf(name);
  if (index === -1) return undefined;
  return process.argv[index + 1];
}

/** Load the raw catalog from a checked-in snapshot file (offline path). */
export function loadCatalogFromFile(filePath: string): ReturnType<typeof parseCommandCodeCatalog> {
  const raw = JSON.parse(readFileSync(filePath, "utf8")) as unknown;
  return parseCommandCodeCatalog(raw);
}

/** Render `models.generated.ts`; the array is sorted by id for determinism. */
export function renderGeneratedModels(models: readonly ProviderModelConfig[]): string {
  const sorted = [...models].sort((a, b) => a.id.localeCompare(b.id));
  const body = JSON.stringify(sorted, null, 2);
  return [
    "// Auto-generated by scripts/generate-models.ts - do not edit by hand.",
    `// Model count: ${sorted.length}`,
    "",
    'import type { ProviderModelConfig } from "@earendil-works/pi-coding-agent";',
    "",
    `export const GENERATED_MODELS: ProviderModelConfig[] = ${body};`,
    "",
  ].join("\n");
}

/** Render `pricing.generated.ts` from the metadata snapshot (sorted by id). */
export function renderPricing(costs: Record<string, ModelCost>): string {
  const ids = Object.keys(costs).sort();
  const lines: string[] = [
    "/**",
    " * Auto-generated by scripts/generate-models.ts - do not edit by hand.",
    " * Per-1M-token USD rates merged from catalog.metadata.ts.",
    ` * Verified: ${METADATA_LAST_VERIFIED}`,
    " */",
    "",
    'import type { ModelCost } from "@earendil-works/pi-ai";',
    "",
    `export const PRICING_LAST_VERIFIED = ${JSON.stringify(METADATA_LAST_VERIFIED)};`,
    "",
    "export const MODEL_COSTS: Record<string, ModelCost> = {",
  ];
  for (const id of ids) {
    const cost = costs[id];
    lines.push(
      `  ${JSON.stringify(id)}: { input: ${cost.input}, output: ${cost.output}, cacheRead: ${cost.cacheRead}, cacheWrite: ${cost.cacheWrite} },`,
    );
  }
  lines.push("};", "");
  return lines.join("\n");
}

function costsFromMetadata(): Record<string, ModelCost> {
  const costs: Record<string, ModelCost> = {};
  for (const [id, meta] of Object.entries(CATALOG_METADATA)) {
    costs[id] = meta.cost;
  }
  return costs;
}

function formatGeneratedFile(filePath: string): void {
  const biome = join(ROOT, "node_modules", ".bin", "biome");
  spawnSync(biome, ["format", "--write", filePath], { cwd: ROOT, stdio: "ignore" });
}

async function main(): Promise<void> {
  const fromFile = readArg("--from-file");
  const raw = fromFile ? loadCatalogFromFile(resolve(process.cwd(), fromFile)) : await fetchCommandCodeModels();
  const models = assembleModels(raw);
  if (models.length === 0) {
    throw new Error("generate-models: refusing to write an empty catalog");
  }

  writeFileSync(MODELS_FILE, renderGeneratedModels(models));
  writeFileSync(PRICING_FILE, renderPricing(costsFromMetadata()));
  formatGeneratedFile(MODELS_FILE);
  formatGeneratedFile(PRICING_FILE);
  console.log(
    `generate-models: wrote models.generated.ts (${models.length} models${fromFile ? `, from ${fromFile}` : ""}) and pricing.generated.ts`,
  );
}

if (process.argv[1] && fileURLToPath(import.meta.url) === resolve(process.argv[1])) {
  main().catch((error: unknown) => {
    console.error(error instanceof Error ? error.message : String(error));
    process.exitCode = 1;
  });
}
