/**
 * Regenerate `catalog.metadata.ts` and `pricing.generated.ts` from the
 * checked-in CLI-snapshot source table (`scripts/metadata.source.json`).
 *
 * The source table is deterministic input, so this script is offline and
 * reproducible: `npm run generate-metadata`. It never contacts the network.
 *
 * The source fields come from the bundled Command Code CLI model registry
 * (`command-code-knowledge/reference/models.md`: per-model reasoning efforts
 * and advertised per-1M-token rates) plus the capability badges on
 * `commandcode.ai/docs/resources/pricing-limits` (vision input). The public
 * `/provider/v1/models` catalog does not expose any of these.
 */

import { spawnSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

interface MetadataCost {
  input: number;
  output: number;
  cacheRead: number;
  cacheWrite: number;
}

interface MetadataSourceModel {
  name: string;
  reasoning: boolean;
  efforts: string[] | null;
  input: string[];
  cost: MetadataCost;
}

interface MetadataSource {
  verifiedAt: string;
  source: string;
  models: Record<string, MetadataSourceModel>;
}

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, "..");
const SOURCE_FILE = join(HERE, "metadata.source.json");
const CATALOG_FILE = join(ROOT, "catalog.metadata.ts");
const PRICING_FILE = join(ROOT, "pricing.generated.ts");

function fail(message: string): never {
  throw new Error(`generate-metadata: ${message}`);
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function readNumber(value: unknown, field: string, id: string): number {
  if (typeof value !== "number" || !Number.isFinite(value)) fail(`${id}: ${field} must be a finite number`);
  return value;
}

/** Parse and validate the checked-in source table. */
export function loadMetadataSource(filePath: string = SOURCE_FILE): MetadataSource {
  let parsed: unknown;
  try {
    parsed = JSON.parse(readFileSync(filePath, "utf8"));
  } catch (error) {
    fail(`cannot read ${filePath}: ${error instanceof Error ? error.message : String(error)}`);
  }
  if (!isRecord(parsed)) fail("source table must be a JSON object");
  const verifiedAt = parsed.verifiedAt;
  const source = parsed.source;
  const modelsRaw = parsed.models;
  if (typeof verifiedAt !== "string" || !verifiedAt) fail("source table is missing verifiedAt");
  if (typeof source !== "string" || !source) fail("source table is missing source");
  if (!isRecord(modelsRaw)) fail("source table is missing models");

  const models: Record<string, MetadataSourceModel> = {};
  for (const [id, value] of Object.entries(modelsRaw)) {
    if (!id) fail("source table contains an empty model id");
    if (!isRecord(value)) fail(`${id}: entry must be an object`);
    if (typeof value.reasoning !== "boolean") fail(`${id}: reasoning must be a boolean`);
    const efforts = value.efforts === null || value.efforts === undefined ? null : value.efforts;
    if (efforts !== null && (!Array.isArray(efforts) || efforts.some((e) => typeof e !== "string"))) {
      fail(`${id}: efforts must be null or a string array`);
    }
    if (!Array.isArray(value.input) || value.input.some((i) => typeof i !== "string")) {
      fail(`${id}: input must be a string array`);
    }
    if (!isRecord(value.cost)) fail(`${id}: cost must be an object`);
    models[id] = {
      name: typeof value.name === "string" ? value.name : id,
      reasoning: value.reasoning,
      efforts: efforts as string[] | null,
      input: value.input as string[],
      cost: {
        input: readNumber(value.cost.input, "cost.input", id),
        output: readNumber(value.cost.output, "cost.output", id),
        cacheRead: readNumber(value.cost.cacheRead, "cost.cacheRead", id),
        cacheWrite: readNumber(value.cost.cacheWrite, "cost.cacheWrite", id),
      },
    };
  }
  if (Object.keys(models).length === 0) fail("source table has no models");
  return { verifiedAt, source, models };
}

/** Render `catalog.metadata.ts`. */
export function renderCatalogMetadata(source: MetadataSource): string {
  const ids = Object.keys(source.models).sort();
  const lines: string[] = [
    "/**",
    " * Auto-generated by scripts/generate-metadata.ts - do not edit by hand.",
    ` * Source: ${source.source}`,
    ` * Verified: ${source.verifiedAt}`,
    " */",
    "",
    'import type { ModelCost } from "@earendil-works/pi-ai";',
    'import { DEFAULT_MAX_OUTPUT_TOKENS } from "./constants.ts";',
    "",
    `export const METADATA_LAST_VERIFIED = ${JSON.stringify(source.verifiedAt)};`,
    "",
    "export const ZERO_COST: ModelCost = { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 };",
    "",
    "export interface CatalogModelMetadata {",
    "  reasoning: boolean;",
    "  efforts?: readonly string[];",
    '  input: ("text" | "image")[];',
    "  maxOutputTokens: number;",
    "  cost: ModelCost;",
    "}",
    "",
    "export const CATALOG_METADATA: Record<string, CatalogModelMetadata> = {",
  ];
  for (const id of ids) {
    const model = source.models[id];
    lines.push(`  ${JSON.stringify(id)}: {`);
    lines.push(`    reasoning: ${model.reasoning},`);
    if (model.efforts && model.efforts.length > 0) {
      lines.push(`    efforts: [${model.efforts.map((effort) => JSON.stringify(effort)).join(", ")}],`);
    }
    lines.push(`    input: [${model.input.map((modality) => JSON.stringify(modality)).join(", ")}],`);
    lines.push("    maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS,");
    lines.push(
      `    cost: { input: ${model.cost.input}, output: ${model.cost.output}, cacheRead: ${model.cost.cacheRead}, cacheWrite: ${model.cost.cacheWrite} },`,
    );
    lines.push("  },");
  }
  lines.push(
    "};",
    "",
    "/**",
    " * Static metadata for a model id. Unknown ids degrade to a text-only,",
    " * non-reasoning model with zero cost and the default output-token budget;",
    " * callers clamp maxTokens against the catalog's context_length.",
    " */",
    "export function metadataForModel(id: string): CatalogModelMetadata {",
    "  if (Object.hasOwn(CATALOG_METADATA, id)) return CATALOG_METADATA[id];",
    '  return { reasoning: false, input: ["text"], maxOutputTokens: DEFAULT_MAX_OUTPUT_TOKENS, cost: ZERO_COST };',
    "}",
    "",
  );
  return lines.join("\n");
}

/** Render `pricing.generated.ts` from the same source table. */
export function renderPricing(source: MetadataSource): string {
  const ids = Object.keys(source.models).sort();
  const lines: string[] = [
    "/**",
    " * Auto-generated by scripts/generate-metadata.ts - do not edit by hand.",
    " * Per-1M-token USD rates from the Command Code model registry.",
    ` * Verified: ${source.verifiedAt}`,
    " */",
    "",
    'import type { ModelCost } from "@earendil-works/pi-ai";',
    "",
    `export const PRICING_LAST_VERIFIED = ${JSON.stringify(source.verifiedAt)};`,
    "",
    "export const MODEL_COSTS: Record<string, ModelCost> = {",
  ];
  for (const id of ids) {
    const { cost } = source.models[id];
    lines.push(
      `  ${JSON.stringify(id)}: { input: ${cost.input}, output: ${cost.output}, cacheRead: ${cost.cacheRead}, cacheWrite: ${cost.cacheWrite} },`,
    );
  }
  lines.push("};", "");
  return lines.join("\n");
}

/** Best-effort biome format of a generated file; ignored when biome is unavailable. */
export function formatGeneratedFile(filePath: string): void {
  const biome = join(ROOT, "node_modules", ".bin", "biome");
  spawnSync(biome, ["format", "--write", filePath], { cwd: ROOT, stdio: "ignore" });
}

function main(): void {
  const source = loadMetadataSource();
  writeFileSync(CATALOG_FILE, renderCatalogMetadata(source));
  writeFileSync(PRICING_FILE, renderPricing(source));
  formatGeneratedFile(CATALOG_FILE);
  formatGeneratedFile(PRICING_FILE);
  console.log(
    `generate-metadata: wrote catalog.metadata.ts (${Object.keys(source.models).length} models) and pricing.generated.ts`,
  );
}

if (process.argv[1] && fileURLToPath(import.meta.url) === resolve(process.argv[1])) {
  main();
}
