#!/usr/bin/env tsx
/**
 * Fetches per-model reasoning options from models.dev and writes
 * reasoning.generated.ts. Run manually (or via CI) and commit the output.
 *
 * Usage:
 *   npm run generate-reasoning
 *
 * The Ollama Cloud API exposes only a boolean `thinking` capability and a
 * global reasoning_effort vocabulary; it does not report which levels each
 * model supports (see models.ts and the reasoning-levels tests). models.dev
 * tracks per-model `reasoning_options` for the `ollama-cloud` provider, which
 * pi also sources for its built-in providers. This script mirrors that: it
 * pulls the `ollama-cloud` provider's `reasoning_options` for each model and
 * writes them verbatim to reasoning.generated.ts as the data source that
 * resolve() in thinking-levels.ts consumes.
 *
 * The table is keyed by the models.dev model id (bare or `:tag`-suffixed), and
 * thinking-levels.ts matches a catalog id by exact name then by `:tag` family,
 * the same way pricing.generated.ts resolves prices. Models with no models.dev
 * entry fall back to the DEFAULT map at runtime.
 *
 * Not shipped at runtime; the generated reasoning.generated.ts is.
 */

import { writeFileSync } from "node:fs";

const MODELS_DEV_URL = "https://models.dev/api.json";
const TIMEOUT_MS = 15000;

export type ModelsDevReasoningOption =
  | { type: "toggle" }
  | {
      type: "effort";
      values: Array<"none" | "minimal" | "low" | "medium" | "high" | "xhigh" | "max" | "default" | null>;
    };

async function fetchModelsDev(): Promise<
  Record<string, { models: Record<string, { reasoning_options?: ModelsDevReasoningOption[] }> }>
> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), TIMEOUT_MS);
  try {
    const res = await fetch(MODELS_DEV_URL, { signal: controller.signal });
    if (!res.ok) {
      throw new Error(`models.dev returned ${res.status}`);
    }
    return await res.json();
  } finally {
    clearTimeout(timer);
  }
}

async function main(): Promise<void> {
  console.log(`Fetching ${MODELS_DEV_URL}...`);
  const data = await fetchModelsDev();
  const ollama = data["ollama-cloud"];
  if (!ollama?.models) {
    throw new Error("models.dev: no ollama-cloud provider models found");
  }

  const optionsByModel = ollama.models;
  const ids = Object.keys(optionsByModel).sort();
  const lines = [
    "// Auto-generated by scripts/generate-reasoning.ts",
    "// Do not edit manually.",
    `// Model count: ${ids.length}`,
    "",
    "export type ModelsDevReasoningOption =",
    '  | { type: "toggle" }',
    '  | { type: "effort"; values: Array<"none" | "minimal" | "low" | "medium" | "high" | "xhigh" | "max" | "default" | null> };',
    "",
    "export const MODEL_REASONING_OPTIONS: Record<string, ModelsDevReasoningOption[]> = {",
  ];
  for (const id of ids) {
    const options = optionsByModel[id].reasoning_options;
    if (options === undefined) continue;
    lines.push(`  ${JSON.stringify(id)}: ${JSON.stringify(options)},`);
  }

  const emitted = Object.keys(optionsByModel).filter((id) => optionsByModel[id].reasoning_options !== undefined).length;
  lines.push("};", "");

  writeFileSync(new URL("../reasoning.generated.ts", import.meta.url), lines.join("\n"));
  console.log(`Wrote reasoning.generated.ts (${emitted} models with reasoning_options).`);
}

await main();
