#!/usr/bin/env tsx
/**
 * Fetches per-model reasoning options from models.dev and writes
 * reasoning.generated.ts. Run manually (or via CI) and commit the output.
 *
 * Usage:
 *   npm run generate-reasoning
 *
 * The Ollama Cloud API exposes only a boolean `thinking` capability and a
 * global reasoning_effort vocabulary; it does not report which levels each
 * model supports (see models.ts and the reasoning-levels tests). models.dev
 * tracks per-model `reasoning_options` for the `ollama-cloud` provider, which
 * pi also sources for its built-in providers. This script mirrors that: it
 * pulls the `ollama-cloud` provider's `reasoning_options` for each model and
 * writes them verbatim to reasoning.generated.ts as the data source that
 * resolve() in thinking-levels.ts consumes.
 *
 * The table is keyed by the models.dev model id (bare or `:tag`-suffixed), and
 * thinking-levels.ts matches a catalog id by exact name then by `:tag` family,
 * the same way pricing.generated.ts resolves prices. Models with no models.dev
 * entry fall back to the DEFAULT map at runtime.
 *
 * Not shipped at runtime; the generated reasoning.generated.ts is.
 */

import { writeFileSync } from "node:fs";

const MODELS_DEV_URL = "https://models.dev/api.json";
const TIMEOUT_MS = 15000;

export type ModelsDevReasoningOption =
  | { type: "toggle" }
  | {
      type: "effort";
      values: Array<"none" | "minimal" | "low" | "medium" | "high" | "xhigh" | "max" | "ultra" | "default" | null>;
    };

/** Valid effort values the generated union accepts (used for payload checks). */
const EFFORT_VALUES = new Set(["none", "minimal", "low", "medium", "high", "xhigh", "max", "ultra"]);

function isModelsDevData(
  value: unknown,
): value is Record<string, { models: Record<string, { reasoning_options?: ModelsDevReasoningOption[] }> }> {
  if (typeof value !== "object" || value === null) return false;
  // Only the ollama-cloud provider is consumed; validate it in the shape this
  // script relies on, leaving unrelated providers unchecked.
  const provider = (value as Record<string, unknown>)["ollama-cloud"];
  if (typeof provider !== "object" || provider === null || !("models" in provider)) return false;
  const models = (provider as Record<string, unknown>).models;
  if (typeof models !== "object" || models === null) return false;
  for (const model of Object.values(models as Record<string, unknown>)) {
    if (typeof model !== "object" || model === null) return false;
    const options = (model as { reasoning_options?: unknown }).reasoning_options;
    if (options === undefined || options === null) continue;
    if (!Array.isArray(options)) return false;
    for (const option of options) {
      if (typeof option !== "object" || option === null) return false;
      const { type, values } = option as { type?: unknown; values?: unknown };
      if (type !== "toggle") {
        if (type !== "effort" || !Array.isArray(values)) return false;
        for (const v of values) {
          if (v !== null && v !== "default" && !EFFORT_VALUES.has(v as string)) return false;
        }
      }
    }
  }
  return true;
}

async function fetchModelsDev(): Promise<
  Record<string, { models: Record<string, { reasoning_options?: ModelsDevReasoningOption[] }> }>
> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), TIMEOUT_MS);
  try {
    const res = await fetch(MODELS_DEV_URL, { signal: controller.signal });
    if (!res.ok) {
      throw new Error(`models.dev returned ${res.status}`);
    }
    const data: unknown = await res.json();
    if (!isModelsDevData(data)) {
      throw new Error("models.dev response failed validation; refusing to overwrite reasoning.generated.ts");
    }
    return data;
  } finally {
    clearTimeout(timer);
  }
}

async function main(): Promise<void> {
  console.log(`Fetching ${MODELS_DEV_URL}...`);
  const data = await fetchModelsDev();
  const ollama = data["ollama-cloud"];
  if (!ollama?.models) {
    throw new Error("models.dev: no ollama-cloud provider models found");
  }

  const optionsByModel = ollama.models;
  const ids = Object.keys(optionsByModel).sort();
  const lines = [
    "// Auto-generated by scripts/generate-reasoning.ts",
    "// Do not edit manually.",
    `// Model count: ${ids.length}`,
    "",
    "export type ModelsDevReasoningOption =",
    '  | { type: "toggle" }',
    '  | { type: "effort"; values: Array<"none" | "minimal" | "low" | "medium" | "high" | "xhigh" | "max" | "ultra" | "default" | null> };',
    "",
    "export const MODEL_REASONING_OPTIONS: Record<string, ModelsDevReasoningOption[]> = {",
  ];
  for (const id of ids) {
    const options = optionsByModel[id].reasoning_options;
    if (options === undefined) continue;
    lines.push(`  ${JSON.stringify(id)}: ${JSON.stringify(options)},`);
  }

  const emitted = Object.keys(optionsByModel).filter((id) => optionsByModel[id].reasoning_options !== undefined).length;
  lines.push("};", "");

  writeFileSync(new URL("../reasoning.generated.ts", import.meta.url), lines.join("\n"));
  console.log(`Wrote reasoning.generated.ts (${emitted} models with reasoning_options).`);
}

await main();
